### ISSUE TITLE
Unknown dependencies versions

### ISSUE THREAD

**Issue by wotori** [suraneti/real-time-speech-translator#10]
Hello! I am now getting the error.
```
ImportError: cannot import name 'enums' from 'google.cloud.speech'
```
Perhaps if you specify a list of package versions that you using, everything will work.

**Comment by suraneti** [comment]
@wotori Hi, I've updated [requirements.txt](https://github.com/suraneti/real-time-speech-translator/blob/master/requirements.txt) with a package version.

**Comment by wotori** [comment]
@suraneti thanks for updates.
Still have no success. Looks like there is no google-cloud-translate==3.0.2 

```
(venv2) C:\Users\wotori\code\real-time-speech-translator>pip install -r requirements.txt --no-cache-dir
Collecting google-cloud-speech==1.3.2
  Downloading google_cloud_speech-1.3.2-py2.py3-none-any.whl (88 kB)
     |████████████████████████████████| 88 kB 422 kB/s
ERROR: Could not find a version that satisfies the requirement google-cloud-translate==3.0.2 (from -r requirements.txt (line 2)) (from versions: 0.20.0, 0.21.0, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 1.1.0, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 2.0.0, 2.0.1, 2.0.2, 3.0.0, 3.0.1)
ERROR: No matching distribution found for google-cloud-translate==3.0.2 (from -r requirements.txt (line 2))
```

**Comment by wotori** [comment]
after replacing to google-cloud-translate==3.0.1 got installed all requirements.
Got a problem only with pyaudio.
If anyone got stuck with this [there is a binary files](https://www.lfd.uci.edu/~gohlke/pythonlibs/) for quick install with no need to build the source.

**Comment by wotori** [comment]
everething seems fine now, thanks!
